<template>
  <div class="page">
    <div class="page-head"><div><h1 class="page-title">运行总览</h1><p class="page-subtitle">实时通信、智能治理与平台健康度的统一视图</p></div><div class="head-actions"><button class="btn" @click="load"><RefreshCw :size="15"/>刷新</button><button class="btn btn-primary" @click="exportReport"><Download :size="15"/>导出报告</button></div></div>
    <div v-if="error" class="notice-card">{{error}}<span>请确认 Go 服务已合入 backend_patch 并以超级管理员账号登录。</span></div>
    <div class="kpi-grid">
      <MetricCard label="在线用户" :value="o.users?.online" :delta="o.users?.delta" hint="当前 WebSocket 在线" :icon="Users" tone="primary"/>
      <MetricCard label="今日消息" :value="o.messages?.today" :delta="o.messages?.delta" hint="文本 / 文件 / Agent" :icon="MessagesSquare" tone="success"/>
      <MetricCard label="活跃群聊" :value="o.rooms?.active" :delta="o.rooms?.delta" hint="24 小时内有消息" :icon="Network" tone="purple"/>
      <MetricCard label="违规事件" :value="o.moderation?.violations" :hint="`${o.moderation?.violation_rate ?? '—'}% 违规率`" :icon="ShieldAlert" tone="warning"/>
    </div>
    <div class="chart-grid">
      <ChartCard title="消息流量趋势" subtitle="24 小时消息吞吐与 Agent 调用"><BaseChart :option="trafficOption"/></ChartCard>
      <ChartCard title="消息构成" subtitle="今日消息类型占比"><BaseChart :option="typeOption"/></ChartCard>
    </div>
    <div class="ops-grid">
      <section class="app-card panel"><div class="panel-title"><div><h3>实时运行指标</h3><p>WebSocket / API / Go Runtime</p></div><Activity :size="17"/></div><div class="runtime-grid"><div><span>WS Connections</span><b>{{fmt(o.runtime?.ws_connections)}}</b></div><div><span>Messages / min</span><b>{{fmt(o.messages?.per_minute)}}</b></div><div><span>API P95</span><b>{{o.runtime?.api_p95_ms ?? '—'}} ms</b></div><div><span>Goroutines</span><b>{{fmt(o.runtime?.goroutines)}}</b></div><div><span>Heap</span><b>{{o.runtime?.heap_mb ?? '—'}} MB</b></div><div><span>Error rate</span><b>{{o.runtime?.error_rate ?? '—'}}%</b></div></div></section>
      <section class="app-card panel"><div class="panel-title"><div><h3>Agent 运行质量</h3><p>模型、RAG 与 Tool Calling</p></div><Bot :size="17"/></div><div class="agent-main"><div class="agent-score"><strong>{{o.agent?.success_rate ?? '—'}}<small>%</small></strong><span>成功率</span></div><div class="agent-list"><div><span>今日调用</span><b>{{fmt(o.agent?.calls)}}</b></div><div><span>P95 延迟</span><b>{{o.agent?.p95_ms ?? '—'}} ms</b></div><div><span>Token</span><b>{{fmt(o.agent?.tokens)}}</b></div></div></div></section>
    </div>
    <div class="two-col">
      <section class="app-card panel"><div class="panel-title"><div><h3>依赖服务健康度</h3><p>最近一次主动探测</p></div><ServerCog :size="17"/></div><div class="health-list"><div v-for="h in o.health||[]" :key="h.name"><div><span class="health-dot" :class="h.status"></span><b>{{h.name}}</b></div><StatusBadge :tone="h.status==='healthy'?'success':h.status==='degraded'?'warning':'danger'">{{h.status}}</StatusBadge><span>{{h.latency_ms}} ms</span></div><div v-if="!(o.health||[]).length" class="empty-row">暂无健康检查数据</div></div></section>
      <section class="app-card panel"><div class="panel-title"><div><h3>告警与异常</h3><p>需要管理员关注的最新事件</p></div><BellRing :size="17"/></div><div class="alerts"><div v-for="a in o.alerts||[]" :key="a.id" class="alert"><div class="alert-icon" :class="a.level"><TriangleAlert :size="15"/></div><div><b>{{a.title}}</b><p>{{a.detail}}</p></div><span>{{a.time}}</span></div><div v-if="!(o.alerts||[]).length" class="empty-row">当前没有未处理告警</div></div></section>
    </div>
  </div>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {Users,MessagesSquare,Network,ShieldAlert,RefreshCw,Download,Activity,Bot,ServerCog,BellRing,TriangleAlert} from 'lucide-vue-next';import MetricCard from '../../components/admin/MetricCard.vue';import ChartCard from '../../components/admin/ChartCard.vue';import BaseChart from '../../components/charts/BaseChart.vue';import StatusBadge from '../../components/common/StatusBadge.vue';import {adminApi} from '../../api/admin.js'
const o=ref({}),error=ref('');const fmt=v=>v==null?'—':new Intl.NumberFormat('zh-CN',{notation:Number(v)>9999?'compact':'standard',maximumFractionDigits:1}).format(v)
async function load(){error.value='';try{o.value=await adminApi.overview()||{}}catch(e){error.value=e.message;o.value={}}}
function exportReport(){const blob=new Blob([JSON.stringify(o.value,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`lan-im-admin-report-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
onMounted(load)
const common={textStyle:{color:'#8993a4'},tooltip:{trigger:'axis',backgroundColor:'#172033',borderWidth:0,textStyle:{color:'#fff'}},grid:{left:18,right:18,top:30,bottom:20,containLabel:true}}
const trafficOption=computed(()=>({...common,xAxis:{type:'category',data:(o.value.message_trend||[]).map(x=>x.time),axisLine:{lineStyle:{color:'#e7ebf1'}},axisLabel:{color:'#8993a4'}},yAxis:{type:'value',splitLine:{lineStyle:{color:'#eef1f5'}},axisLabel:{color:'#8993a4'}},series:[{name:'消息',type:'line',smooth:true,showSymbol:false,data:(o.value.message_trend||[]).map(x=>x.messages),lineStyle:{width:2,color:'#3159e8'},areaStyle:{color:{type:'linear',x:0,y:0,x2:0,y2:1,colorStops:[{offset:0,color:'rgba(49,89,232,.18)'},{offset:1,color:'rgba(49,89,232,0)'}]}}},{name:'Agent',type:'line',smooth:true,showSymbol:false,data:(o.value.message_trend||[]).map(x=>x.agent),lineStyle:{width:2,color:'#0f9d6c'}}]}))
const typeOption=computed(()=>({tooltip:{trigger:'item'},legend:{bottom:0,textStyle:{color:'#8993a4'},itemWidth:8,itemHeight:8},series:[{type:'pie',radius:['56%','78%'],center:['50%','44%'],itemStyle:{borderColor:'var(--surface)',borderWidth:3,borderRadius:6},label:{show:false},data:o.value.message_types||[]}]}))
</script>
<style scoped>
.page{display:grid;gap:14px}.page-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:4px}.head-actions{display:flex;gap:8px;align-items:center}.notice-card{padding:11px 13px;border-radius:10px;background:var(--warning-soft);color:var(--warning);font-size:12px}.notice-card span{display:block;margin-top:4px;color:var(--text-2)}.ops-grid{display:grid;grid-template-columns:1.3fr .7fr;gap:14px}.panel{padding:17px 18px}.panel-title{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:14px;color:var(--text-2)}.panel-title h3{margin:0;color:var(--text);font-size:14px}.panel-title p{margin:4px 0 0;color:var(--text-3);font-size:11px}.runtime-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.runtime-grid>div{padding:12px;border-radius:9px;background:var(--surface-soft)}.runtime-grid span,.runtime-grid b{display:block}.runtime-grid span{font-size:10px;color:var(--text-3);margin-bottom:6px}.runtime-grid b{font-size:16px}.agent-main{display:grid;grid-template-columns:110px 1fr;gap:14px}.agent-score{border-radius:12px;background:var(--success-soft);display:grid;place-items:center;align-content:center;min-height:126px;color:var(--success)}.agent-score strong{font-size:28px}.agent-score small{font-size:12px}.agent-score span{font-size:10px;margin-top:3px}.agent-list{display:grid;gap:8px}.agent-list div{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line);font-size:11px}.agent-list div:last-child{border:0}.agent-list span{color:var(--text-3)}.health-list>div{display:grid;grid-template-columns:1fr auto 70px;align-items:center;gap:12px;padding:9px 0;border-bottom:1px solid var(--line);font-size:11px}.health-list>div:last-child{border:0}.health-list>div>div{display:flex;align-items:center;gap:8px}.health-list>div>span:last-child{text-align:right;color:var(--text-3)}.health-dot{width:7px;height:7px;border-radius:50%;background:var(--text-3)}.health-dot.healthy{background:var(--success)}.health-dot.degraded{background:var(--warning)}.health-dot.down{background:var(--danger)}.alerts{display:grid;gap:3px}.alert{display:grid;grid-template-columns:32px 1fr auto;gap:9px;align-items:center;padding:9px;border-radius:9px}.alert:hover{background:var(--surface-soft)}.alert-icon{width:30px;height:30px;border-radius:9px;display:grid;place-items:center;background:var(--warning-soft);color:var(--warning)}.alert-icon.info{background:var(--primary-soft);color:var(--primary)}.alert b{font-size:11px}.alert p{margin:3px 0 0;font-size:10px;color:var(--text-3)}.alert>span{font-size:10px;color:var(--text-3)}.empty-row{padding:22px!important;text-align:center!important;color:var(--text-3)!important;display:block!important}.chart-grid{margin-top:0}@media(max-width:1180px){.ops-grid{grid-template-columns:1fr}}@media(max-width:720px){.page-head{flex-direction:column}.head-actions{width:100%;overflow:auto}.runtime-grid{grid-template-columns:repeat(2,1fr)}}
</style>
