<template>
  <div class="page">
    <div class="page-head"><div><h1 class="page-title">运维事件</h1><p class="page-subtitle">告警、系统错误与 Agent Tool Calling 记录</p></div><button class="btn" @click="load"><RefreshCw :size="14"/>刷新</button></div>
    <div class="tabs"><button v-for="item in tabs" :key="item.id" :class="{active:tab===item.id}" @click="tab=item.id;load()">{{item.label}}</button></div>
    <section class="app-card">
      <div v-if="tab==='alerts'" class="panel"><div class="panel-actions"><button class="btn" @click="evaluate">立即评估</button><StatusBadge :tone="error?'danger':'success'">{{error||`${rows.length} 条`}}</StatusBadge></div><div class="table-wrap"><table class="data-table"><thead><tr><th>级别</th><th>来源</th><th>告警</th><th>状态</th><th>时间</th><th></th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><StatusBadge :tone="row.level==='critical'?'danger':row.level==='warning'?'warning':'neutral'">{{row.level}}</StatusBadge></td><td>{{row.source}}</td><td><b>{{row.name}}</b><small>{{row.message}}</small></td><td>{{row.status}}</td><td>{{fmtTime(row.created_at)}}</td><td><button v-if="row.status!=='resolved'" class="btn btn-sm" @click="resolveAlert(row)">标记解决</button></td></tr><tr v-if="!rows.length"><td colspan="6" class="empty">暂无告警</td></tr></tbody></table></div></div>
      <div v-else-if="tab==='errors'" class="panel"><div class="panel-actions"><select v-model="resolved" class="select" @change="load"><option value="">全部状态</option><option value="false">未处理</option><option value="true">已处理</option></select><StatusBadge :tone="error?'danger':'success'">{{error||`${rows.length} 条`}}</StatusBadge></div><div class="table-wrap"><table class="data-table"><thead><tr><th>模块</th><th>类型</th><th>错误</th><th>Request ID</th><th>状态</th><th>时间</th><th></th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{row.module}}</td><td>{{row.error_type}}</td><td><span class="ellipsis">{{row.error_message}}</span></td><td><code>{{row.request_id||'—'}}</code></td><td>{{row.resolved?'已处理':'未处理'}}</td><td>{{fmtTime(row.timestamp||row.created_at)}}</td><td><button v-if="!row.resolved" class="btn btn-sm" @click="resolveError(row)">处理</button></td></tr><tr v-if="!rows.length"><td colspan="7" class="empty">暂无错误</td></tr></tbody></table></div></div>
      <div v-else class="panel"><div class="panel-actions"><input v-model="toolName" class="input tool-filter" placeholder="Tool 名称" @keyup.enter="load"/><StatusBadge :tone="error?'danger':'success'">{{error||`${rows.length} 条`}}</StatusBadge></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Tool</th><th>用户 / 房间</th><th>耗时</th><th>结果</th><th>错误</th><th>时间</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><b>{{row.tool_name}}</b><small>{{row.tool_call_id}}</small></td><td>User #{{row.user_id}}<small>Room #{{row.room_id}}</small></td><td>{{row.latency_ms}} ms</td><td><StatusBadge :tone="row.success?'success':'danger'">{{row.success?'成功':'失败'}}</StatusBadge></td><td>{{row.error||'—'}}</td><td>{{fmtTime(row.started_at||row.created_at)}}</td></tr><tr v-if="!rows.length"><td colspan="6" class="empty">暂无 Tool Call</td></tr></tbody></table></div></div>
    </section>
  </div>
</template>
<script setup>
import{onMounted,ref}from'vue';import{RefreshCw}from'lucide-vue-next';import StatusBadge from'../../components/common/StatusBadge.vue';import{adminApi}from'../../api/admin.js';
const tabs=[{id:'alerts',label:'告警中心'},{id:'errors',label:'系统错误'},{id:'tools',label:'Tool Calls'}];const tab=ref('alerts'),rows=ref([]),error=ref(''),resolved=ref(''),toolName=ref('');const fmtTime=v=>v?new Date(v).toLocaleString('zh-CN'):'—';
async function load(){error.value='';try{let d;if(tab.value==='alerts')d=await adminApi.alerts();else if(tab.value==='errors')d=await adminApi.errors({resolved:resolved.value});else d=await adminApi.toolCalls({tool_name:toolName.value});rows.value=d?.items||[]}catch(e){rows.value=[];error.value=e.message}}
async function evaluate(){try{await adminApi.evaluateAlerts();await load()}catch(e){alert(e.message)}}async function resolveAlert(row){try{await adminApi.resolveAlert(row.id);await load()}catch(e){alert(e.message)}}async function resolveError(row){try{await adminApi.resolveError(row.id);await load()}catch(e){alert(e.message)}}onMounted(load)
</script>
<style scoped>.page{display:grid;gap:14px}.page-head,.panel-actions{display:flex;justify-content:space-between;align-items:center}.tabs{display:flex;gap:5px;border-bottom:1px solid var(--line)}.tabs button{border:0;background:transparent;color:var(--text-2);padding:10px 14px;border-bottom:2px solid transparent}.tabs button.active{color:var(--primary);border-color:var(--primary);font-weight:700}.panel-actions{padding:14px}.select{width:150px}.tool-filter{width:240px}.ellipsis{display:block;max-width:360px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}td small{display:block;color:var(--text-3);font-size:10px;margin-top:3px}.empty{text-align:center!important;color:var(--text-3);padding:30px!important}</style>
