ARG DOCKER_HUB_MIRROR=dockerproxy.net
FROM ${DOCKER_HUB_MIRROR}/library/nginx:alpine

# 复制 Nginx 网关配置
COPY ./deploy/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./deploy/nginx/templates /etc/nginx/templates
