// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRuntimeConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SystemPrompt      string                 `protobuf:"bytes,1,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	TriggerMode       int32                  `protobuf:"varint,2,opt,name=trigger_mode,json=triggerMode,proto3" json:"trigger_mode,omitempty"`
	TriggerWords      []string               `protobuf:"bytes,3,rep,name=trigger_words,json=triggerWords,proto3" json:"trigger_words,omitempty"`
	MaxHistory        int32                  `protobuf:"varint,4,opt,name=max_history,json=maxHistory,proto3" json:"max_history,omitempty"`
	Temperature       float64                `protobuf:"fixed64,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	ModelName         string                 `protobuf:"bytes,6,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	RagEnabled        bool                   `protobuf:"varint,7,opt,name=rag_enabled,json=ragEnabled,proto3" json:"rag_enabled,omitempty"`
	TopK              int32                  `protobuf:"varint,8,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	SimilarityThold   float64                `protobuf:"fixed64,9,opt,name=similarity_thold,json=similarityThold,proto3" json:"similarity_thold,omitempty"`
	RerankEnabled     bool                   `protobuf:"varint,10,opt,name=rerank_enabled,json=rerankEnabled,proto3" json:"rerank_enabled,omitempty"`
	MaxChunkTokens    int32                  `protobuf:"varint,11,opt,name=max_chunk_tokens,json=maxChunkTokens,proto3" json:"max_chunk_tokens,omitempty"`
	TopicChunkMinMsgs int32                  `protobuf:"varint,12,opt,name=topic_chunk_min_msgs,json=topicChunkMinMsgs,proto3" json:"topic_chunk_min_msgs,omitempty"`
	TopicChunkModel   string                 `protobuf:"bytes,13,opt,name=topic_chunk_model,json=topicChunkModel,proto3" json:"topic_chunk_model,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentRuntimeConfig) Reset() {
	*x = AgentRuntimeConfig{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRuntimeConfig) ProtoMessage() {}

func (x *AgentRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRuntimeConfig.ProtoReflect.Descriptor instead.
func (*AgentRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRuntimeConfig) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AgentRuntimeConfig) GetTriggerMode() int32 {
	if x != nil {
		return x.TriggerMode
	}
	return 0
}

func (x *AgentRuntimeConfig) GetTriggerWords() []string {
	if x != nil {
		return x.TriggerWords
	}
	return nil
}

func (x *AgentRuntimeConfig) GetMaxHistory() int32 {
	if x != nil {
		return x.MaxHistory
	}
	return 0
}

func (x *AgentRuntimeConfig) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AgentRuntimeConfig) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AgentRuntimeConfig) GetRagEnabled() bool {
	if x != nil {
		return x.RagEnabled
	}
	return false
}

func (x *AgentRuntimeConfig) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *AgentRuntimeConfig) GetSimilarityThold() float64 {
	if x != nil {
		return x.SimilarityThold
	}
	return 0
}

func (x *AgentRuntimeConfig) GetRerankEnabled() bool {
	if x != nil {
		return x.RerankEnabled
	}
	return false
}

func (x *AgentRuntimeConfig) GetMaxChunkTokens() int32 {
	if x != nil {
		return x.MaxChunkTokens
	}
	return 0
}

func (x *AgentRuntimeConfig) GetTopicChunkMinMsgs() int32 {
	if x != nil {
		return x.TopicChunkMinMsgs
	}
	return 0
}

func (x *AgentRuntimeConfig) GetTopicChunkModel() string {
	if x != nil {
		return x.TopicChunkModel
	}
	return ""
}

type ProcessMessageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoomId            int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	BotUserId         int64                  `protobuf:"varint,2,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	SenderId          int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName        string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content           string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MessageTimeUnixMs int64                  `protobuf:"varint,6,opt,name=message_time_unix_ms,json=messageTimeUnixMs,proto3" json:"message_time_unix_ms,omitempty"`
	Config            *AgentRuntimeConfig    `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	RoomName          string                 `protobuf:"bytes,8,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProcessMessageRequest) Reset() {
	*x = ProcessMessageRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMessageRequest) ProtoMessage() {}

func (x *ProcessMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMessageRequest.ProtoReflect.Descriptor instead.
func (*ProcessMessageRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessMessageRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ProcessMessageRequest) GetBotUserId() int64 {
	if x != nil {
		return x.BotUserId
	}
	return 0
}

func (x *ProcessMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ProcessMessageRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ProcessMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProcessMessageRequest) GetMessageTimeUnixMs() int64 {
	if x != nil {
		return x.MessageTimeUnixMs
	}
	return 0
}

func (x *ProcessMessageRequest) GetConfig() *AgentRuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ProcessMessageRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type ProcessMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Skip          bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMessageResponse) Reset() {
	*x = ProcessMessageResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMessageResponse) ProtoMessage() {}

func (x *ProcessMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMessageResponse.ProtoReflect.Descriptor instead.
func (*ProcessMessageResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessMessageResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ProcessMessageResponse) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *ProcessMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EnableAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	BotUserId     int64                  `protobuf:"varint,2,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	Config        *AgentRuntimeConfig    `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableAgentRequest) Reset() {
	*x = EnableAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableAgentRequest) ProtoMessage() {}

func (x *EnableAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableAgentRequest.ProtoReflect.Descriptor instead.
func (*EnableAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *EnableAgentRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *EnableAgentRequest) GetBotUserId() int64 {
	if x != nil {
		return x.BotUserId
	}
	return 0
}

func (x *EnableAgentRequest) GetConfig() *AgentRuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type EnableAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableAgentResponse) Reset() {
	*x = EnableAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableAgentResponse) ProtoMessage() {}

func (x *EnableAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableAgentResponse.ProtoReflect.Descriptor instead.
func (*EnableAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

type PauseAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseAgentRequest) Reset() {
	*x = PauseAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseAgentRequest) ProtoMessage() {}

func (x *PauseAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseAgentRequest.ProtoReflect.Descriptor instead.
func (*PauseAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PauseAgentRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type PauseAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseAgentResponse) Reset() {
	*x = PauseAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseAgentResponse) ProtoMessage() {}

func (x *PauseAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseAgentResponse.ProtoReflect.Descriptor instead.
func (*PauseAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

type RemoveAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAgentRequest) Reset() {
	*x = RemoveAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentRequest) ProtoMessage() {}

func (x *RemoveAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentRequest.ProtoReflect.Descriptor instead.
func (*RemoveAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveAgentRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RemoveAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAgentResponse) Reset() {
	*x = RemoveAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentResponse) ProtoMessage() {}

func (x *RemoveAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentResponse.ProtoReflect.Descriptor instead.
func (*RemoveAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

type TriggerChunkingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerChunkingRequest) Reset() {
	*x = TriggerChunkingRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerChunkingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerChunkingRequest) ProtoMessage() {}

func (x *TriggerChunkingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerChunkingRequest.ProtoReflect.Descriptor instead.
func (*TriggerChunkingRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *TriggerChunkingRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type TriggerChunkingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChunkedMessages int32                  `protobuf:"varint,1,opt,name=chunked_messages,json=chunkedMessages,proto3" json:"chunked_messages,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TriggerChunkingResponse) Reset() {
	*x = TriggerChunkingResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerChunkingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerChunkingResponse) ProtoMessage() {}

func (x *TriggerChunkingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerChunkingResponse.ProtoReflect.Descriptor instead.
func (*TriggerChunkingResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *TriggerChunkingResponse) GetChunkedMessages() int32 {
	if x != nil {
		return x.ChunkedMessages
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type MessageRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName      string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content         string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageRecord) Reset() {
	*x = MessageRecord{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecord) ProtoMessage() {}

func (x *MessageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecord.ProtoReflect.Descriptor instead.
func (*MessageRecord) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *MessageRecord) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageRecord) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageRecord) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *MessageRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageRecord) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type FetchMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	StartTimeUnixMs int64                  `protobuf:"varint,2,opt,name=start_time_unix_ms,json=startTimeUnixMs,proto3" json:"start_time_unix_ms,omitempty"`
	EndTimeUnixMs   int64                  `protobuf:"varint,3,opt,name=end_time_unix_ms,json=endTimeUnixMs,proto3" json:"end_time_unix_ms,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchMessagesRequest) Reset() {
	*x = FetchMessagesRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessagesRequest) ProtoMessage() {}

func (x *FetchMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessagesRequest.ProtoReflect.Descriptor instead.
func (*FetchMessagesRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *FetchMessagesRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *FetchMessagesRequest) GetStartTimeUnixMs() int64 {
	if x != nil {
		return x.StartTimeUnixMs
	}
	return 0
}

func (x *FetchMessagesRequest) GetEndTimeUnixMs() int64 {
	if x != nil {
		return x.EndTimeUnixMs
	}
	return 0
}

func (x *FetchMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FetchMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageRecord       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMessagesResponse) Reset() {
	*x = FetchMessagesResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessagesResponse) ProtoMessage() {}

func (x *FetchMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessagesResponse.ProtoReflect.Descriptor instead.
func (*FetchMessagesResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *FetchMessagesResponse) GetMessages() []*MessageRecord {
	if x != nil {
		return x.Messages
	}
	return nil
}

type KickUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserRequest) Reset() {
	*x = KickUserRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserRequest) ProtoMessage() {}

func (x *KickUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserRequest.ProtoReflect.Descriptor instead.
func (*KickUserRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *KickUserRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *KickUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KickUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type KickUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserResponse) Reset() {
	*x = KickUserResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserResponse) ProtoMessage() {}

func (x *KickUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserResponse.ProtoReflect.Descriptor instead.
func (*KickUserResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *KickUserResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

func (x *KickUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	BotUserId     int64                  `protobuf:"varint,2,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReplyRequest) Reset() {
	*x = SendReplyRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReplyRequest) ProtoMessage() {}

func (x *SendReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReplyRequest.ProtoReflect.Descriptor instead.
func (*SendReplyRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *SendReplyRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SendReplyRequest) GetBotUserId() int64 {
	if x != nil {
		return x.BotUserId
	}
	return 0
}

func (x *SendReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendReplyRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReplyResponse) Reset() {
	*x = SendReplyResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReplyResponse) ProtoMessage() {}

func (x *SendReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReplyResponse.ProtoReflect.Descriptor instead.
func (*SendReplyResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\x0flan_im.agent.v1\"\xf2\x03\n" +
	"\x12AgentRuntimeConfig\x12#\n" +
	"\rsystem_prompt\x18\x01 \x01(\tR\fsystemPrompt\x12!\n" +
	"\ftrigger_mode\x18\x02 \x01(\x05R\vtriggerMode\x12#\n" +
	"\rtrigger_words\x18\x03 \x03(\tR\ftriggerWords\x12\x1f\n" +
	"\vmax_history\x18\x04 \x01(\x05R\n" +
	"maxHistory\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"model_name\x18\x06 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vrag_enabled\x18\a \x01(\bR\n" +
	"ragEnabled\x12\x13\n" +
	"\x05top_k\x18\b \x01(\x05R\x04topK\x12)\n" +
	"\x10similarity_thold\x18\t \x01(\x01R\x0fsimilarityThold\x12%\n" +
	"\x0ererank_enabled\x18\n" +
	" \x01(\bR\rrerankEnabled\x12(\n" +
	"\x10max_chunk_tokens\x18\v \x01(\x05R\x0emaxChunkTokens\x12/\n" +
	"\x14topic_chunk_min_msgs\x18\f \x01(\x05R\x11topicChunkMinMsgs\x12*\n" +
	"\x11topic_chunk_model\x18\r \x01(\tR\x0ftopicChunkModel\"\xb3\x02\n" +
	"\x15ProcessMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1e\n" +
	"\vbot_user_id\x18\x02 \x01(\x03R\tbotUserId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12/\n" +
	"\x14message_time_unix_ms\x18\x06 \x01(\x03R\x11messageTimeUnixMs\x12;\n" +
	"\x06config\x18\a \x01(\v2#.lan_im.agent.v1.AgentRuntimeConfigR\x06config\x12\x1b\n" +
	"\troom_name\x18\b \x01(\tR\broomName\"X\n" +
	"\x16ProcessMessageResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8a\x01\n" +
	"\x12EnableAgentRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1e\n" +
	"\vbot_user_id\x18\x02 \x01(\x03R\tbotUserId\x12;\n" +
	"\x06config\x18\x03 \x01(\v2#.lan_im.agent.v1.AgentRuntimeConfigR\x06config\"\x15\n" +
	"\x13EnableAgentResponse\",\n" +
	"\x11PauseAgentRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"\x14\n" +
	"\x12PauseAgentResponse\"-\n" +
	"\x12RemoveAgentRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"\x15\n" +
	"\x13RemoveAgentResponse\"1\n" +
	"\x16TriggerChunkingRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"D\n" +
	"\x17TriggerChunkingResponse\x12)\n" +
	"\x10chunked_messages\x18\x01 \x01(\x05R\x0fchunkedMessages\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xb3\x01\n" +
	"\rMessageRecord\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12+\n" +
	"\x12created_at_unix_ms\x18\x05 \x01(\x03R\x0fcreatedAtUnixMs\"\x9b\x01\n" +
	"\x14FetchMessagesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12+\n" +
	"\x12start_time_unix_ms\x18\x02 \x01(\x03R\x0fstartTimeUnixMs\x12'\n" +
	"\x10end_time_unix_ms\x18\x03 \x01(\x03R\rendTimeUnixMs\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"S\n" +
	"\x15FetchMessagesResponse\x12:\n" +
	"\bmessages\x18\x01 \x03(\v2\x1e.lan_im.agent.v1.MessageRecordR\bmessages\"[\n" +
	"\x0fKickUserRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"F\n" +
	"\x10KickUserResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x01\n" +
	"\x10SendReplyRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1e\n" +
	"\vbot_user_id\x18\x02 \x01(\x03R\tbotUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\"\x13\n" +
	"\x11SendReplyResponse2\xad\x04\n" +
	"\fAgentService\x12a\n" +
	"\x0eProcessMessage\x12&.lan_im.agent.v1.ProcessMessageRequest\x1a'.lan_im.agent.v1.ProcessMessageResponse\x12X\n" +
	"\vEnableAgent\x12#.lan_im.agent.v1.EnableAgentRequest\x1a$.lan_im.agent.v1.EnableAgentResponse\x12U\n" +
	"\n" +
	"PauseAgent\x12\".lan_im.agent.v1.PauseAgentRequest\x1a#.lan_im.agent.v1.PauseAgentResponse\x12X\n" +
	"\vRemoveAgent\x12#.lan_im.agent.v1.RemoveAgentRequest\x1a$.lan_im.agent.v1.RemoveAgentResponse\x12d\n" +
	"\x0fTriggerChunking\x12'.lan_im.agent.v1.TriggerChunkingRequest\x1a(.lan_im.agent.v1.TriggerChunkingResponse\x12I\n" +
	"\x06Health\x12\x1e.lan_im.agent.v1.HealthRequest\x1a\x1f.lan_im.agent.v1.HealthResponse2\x90\x02\n" +
	"\tIMService\x12^\n" +
	"\rFetchMessages\x12%.lan_im.agent.v1.FetchMessagesRequest\x1a&.lan_im.agent.v1.FetchMessagesResponse\x12O\n" +
	"\bKickUser\x12 .lan_im.agent.v1.KickUserRequest\x1a!.lan_im.agent.v1.KickUserResponse\x12R\n" +
	"\tSendReply\x12!.lan_im.agent.v1.SendReplyRequest\x1a\".lan_im.agent.v1.SendReplyResponseB\"Z lan-im-go/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_agent_v1_agent_proto_goTypes = []any{
	(*AgentRuntimeConfig)(nil),      // 0: lan_im.agent.v1.AgentRuntimeConfig
	(*ProcessMessageRequest)(nil),   // 1: lan_im.agent.v1.ProcessMessageRequest
	(*ProcessMessageResponse)(nil),  // 2: lan_im.agent.v1.ProcessMessageResponse
	(*EnableAgentRequest)(nil),      // 3: lan_im.agent.v1.EnableAgentRequest
	(*EnableAgentResponse)(nil),     // 4: lan_im.agent.v1.EnableAgentResponse
	(*PauseAgentRequest)(nil),       // 5: lan_im.agent.v1.PauseAgentRequest
	(*PauseAgentResponse)(nil),      // 6: lan_im.agent.v1.PauseAgentResponse
	(*RemoveAgentRequest)(nil),      // 7: lan_im.agent.v1.RemoveAgentRequest
	(*RemoveAgentResponse)(nil),     // 8: lan_im.agent.v1.RemoveAgentResponse
	(*TriggerChunkingRequest)(nil),  // 9: lan_im.agent.v1.TriggerChunkingRequest
	(*TriggerChunkingResponse)(nil), // 10: lan_im.agent.v1.TriggerChunkingResponse
	(*HealthRequest)(nil),           // 11: lan_im.agent.v1.HealthRequest
	(*HealthResponse)(nil),          // 12: lan_im.agent.v1.HealthResponse
	(*MessageRecord)(nil),           // 13: lan_im.agent.v1.MessageRecord
	(*FetchMessagesRequest)(nil),    // 14: lan_im.agent.v1.FetchMessagesRequest
	(*FetchMessagesResponse)(nil),   // 15: lan_im.agent.v1.FetchMessagesResponse
	(*KickUserRequest)(nil),         // 16: lan_im.agent.v1.KickUserRequest
	(*KickUserResponse)(nil),        // 17: lan_im.agent.v1.KickUserResponse
	(*SendReplyRequest)(nil),        // 18: lan_im.agent.v1.SendReplyRequest
	(*SendReplyResponse)(nil),       // 19: lan_im.agent.v1.SendReplyResponse
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	0,  // 0: lan_im.agent.v1.ProcessMessageRequest.config:type_name -> lan_im.agent.v1.AgentRuntimeConfig
	0,  // 1: lan_im.agent.v1.EnableAgentRequest.config:type_name -> lan_im.agent.v1.AgentRuntimeConfig
	13, // 2: lan_im.agent.v1.FetchMessagesResponse.messages:type_name -> lan_im.agent.v1.MessageRecord
	1,  // 3: lan_im.agent.v1.AgentService.ProcessMessage:input_type -> lan_im.agent.v1.ProcessMessageRequest
	3,  // 4: lan_im.agent.v1.AgentService.EnableAgent:input_type -> lan_im.agent.v1.EnableAgentRequest
	5,  // 5: lan_im.agent.v1.AgentService.PauseAgent:input_type -> lan_im.agent.v1.PauseAgentRequest
	7,  // 6: lan_im.agent.v1.AgentService.RemoveAgent:input_type -> lan_im.agent.v1.RemoveAgentRequest
	9,  // 7: lan_im.agent.v1.AgentService.TriggerChunking:input_type -> lan_im.agent.v1.TriggerChunkingRequest
	11, // 8: lan_im.agent.v1.AgentService.Health:input_type -> lan_im.agent.v1.HealthRequest
	14, // 9: lan_im.agent.v1.IMService.FetchMessages:input_type -> lan_im.agent.v1.FetchMessagesRequest
	16, // 10: lan_im.agent.v1.IMService.KickUser:input_type -> lan_im.agent.v1.KickUserRequest
	18, // 11: lan_im.agent.v1.IMService.SendReply:input_type -> lan_im.agent.v1.SendReplyRequest
	2,  // 12: lan_im.agent.v1.AgentService.ProcessMessage:output_type -> lan_im.agent.v1.ProcessMessageResponse
	4,  // 13: lan_im.agent.v1.AgentService.EnableAgent:output_type -> lan_im.agent.v1.EnableAgentResponse
	6,  // 14: lan_im.agent.v1.AgentService.PauseAgent:output_type -> lan_im.agent.v1.PauseAgentResponse
	8,  // 15: lan_im.agent.v1.AgentService.RemoveAgent:output_type -> lan_im.agent.v1.RemoveAgentResponse
	10, // 16: lan_im.agent.v1.AgentService.TriggerChunking:output_type -> lan_im.agent.v1.TriggerChunkingResponse
	12, // 17: lan_im.agent.v1.AgentService.Health:output_type -> lan_im.agent.v1.HealthResponse
	15, // 18: lan_im.agent.v1.IMService.FetchMessages:output_type -> lan_im.agent.v1.FetchMessagesResponse
	17, // 19: lan_im.agent.v1.IMService.KickUser:output_type -> lan_im.agent.v1.KickUserResponse
	19, // 20: lan_im.agent.v1.IMService.SendReply:output_type -> lan_im.agent.v1.SendReplyResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
