// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: admin_control.proto

package admincontrolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminControlService_ListConnections_FullMethodName  = "/lan_im.admincontrol.v1.AdminControlService/ListConnections"
	AdminControlService_CloseConnection_FullMethodName  = "/lan_im.admincontrol.v1.AdminControlService/CloseConnection"
	AdminControlService_KickUser_FullMethodName         = "/lan_im.admincontrol.v1.AdminControlService/KickUser"
	AdminControlService_DisbandRoom_FullMethodName      = "/lan_im.admincontrol.v1.AdminControlService/DisbandRoom"
	AdminControlService_RemoveRoomMember_FullMethodName = "/lan_im.admincontrol.v1.AdminControlService/RemoveRoomMember"
	AdminControlService_HubStats_FullMethodName         = "/lan_im.admincontrol.v1.AdminControlService/HubStats"
	AdminControlService_RuntimeSnapshots_FullMethodName = "/lan_im.admincontrol.v1.AdminControlService/RuntimeSnapshots"
	AdminControlService_AddAgent_FullMethodName         = "/lan_im.admincontrol.v1.AdminControlService/AddAgent"
	AdminControlService_PauseAgent_FullMethodName       = "/lan_im.admincontrol.v1.AdminControlService/PauseAgent"
)

// AdminControlServiceClient is the client API for AdminControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminControlServiceClient interface {
	ListConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConnectionsResponse, error)
	CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*CloseConnectionResponse, error)
	KickUser(ctx context.Context, in *KickUserRequest, opts ...grpc.CallOption) (*KickUserResponse, error)
	DisbandRoom(ctx context.Context, in *DisbandRoomRequest, opts ...grpc.CallOption) (*DisbandRoomResponse, error)
	RemoveRoomMember(ctx context.Context, in *RemoveRoomMemberRequest, opts ...grpc.CallOption) (*RemoveRoomMemberResponse, error)
	HubStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HubStatsResponse, error)
	RuntimeSnapshots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeSnapshotsResponse, error)
	AddAgent(ctx context.Context, in *AddAgentRequest, opts ...grpc.CallOption) (*AddAgentResponse, error)
	PauseAgent(ctx context.Context, in *PauseAgentRequest, opts ...grpc.CallOption) (*PauseAgentResponse, error)
}

type adminControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminControlServiceClient(cc grpc.ClientConnInterface) AdminControlServiceClient {
	return &adminControlServiceClient{cc}
}

func (c *adminControlServiceClient) ListConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectionsResponse)
	err := c.cc.Invoke(ctx, AdminControlService_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*CloseConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseConnectionResponse)
	err := c.cc.Invoke(ctx, AdminControlService_CloseConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) KickUser(ctx context.Context, in *KickUserRequest, opts ...grpc.CallOption) (*KickUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickUserResponse)
	err := c.cc.Invoke(ctx, AdminControlService_KickUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) DisbandRoom(ctx context.Context, in *DisbandRoomRequest, opts ...grpc.CallOption) (*DisbandRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisbandRoomResponse)
	err := c.cc.Invoke(ctx, AdminControlService_DisbandRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) RemoveRoomMember(ctx context.Context, in *RemoveRoomMemberRequest, opts ...grpc.CallOption) (*RemoveRoomMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRoomMemberResponse)
	err := c.cc.Invoke(ctx, AdminControlService_RemoveRoomMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) HubStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HubStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HubStatsResponse)
	err := c.cc.Invoke(ctx, AdminControlService_HubStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) RuntimeSnapshots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeSnapshotsResponse)
	err := c.cc.Invoke(ctx, AdminControlService_RuntimeSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) AddAgent(ctx context.Context, in *AddAgentRequest, opts ...grpc.CallOption) (*AddAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAgentResponse)
	err := c.cc.Invoke(ctx, AdminControlService_AddAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminControlServiceClient) PauseAgent(ctx context.Context, in *PauseAgentRequest, opts ...grpc.CallOption) (*PauseAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseAgentResponse)
	err := c.cc.Invoke(ctx, AdminControlService_PauseAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminControlServiceServer is the server API for AdminControlService service.
// All implementations must embed UnimplementedAdminControlServiceServer
// for forward compatibility.
type AdminControlServiceServer interface {
	ListConnections(context.Context, *emptypb.Empty) (*ListConnectionsResponse, error)
	CloseConnection(context.Context, *CloseConnectionRequest) (*CloseConnectionResponse, error)
	KickUser(context.Context, *KickUserRequest) (*KickUserResponse, error)
	DisbandRoom(context.Context, *DisbandRoomRequest) (*DisbandRoomResponse, error)
	RemoveRoomMember(context.Context, *RemoveRoomMemberRequest) (*RemoveRoomMemberResponse, error)
	HubStats(context.Context, *emptypb.Empty) (*HubStatsResponse, error)
	RuntimeSnapshots(context.Context, *emptypb.Empty) (*RuntimeSnapshotsResponse, error)
	AddAgent(context.Context, *AddAgentRequest) (*AddAgentResponse, error)
	PauseAgent(context.Context, *PauseAgentRequest) (*PauseAgentResponse, error)
	mustEmbedUnimplementedAdminControlServiceServer()
}

// UnimplementedAdminControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminControlServiceServer struct{}

func (UnimplementedAdminControlServiceServer) ListConnections(context.Context, *emptypb.Empty) (*ListConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedAdminControlServiceServer) CloseConnection(context.Context, *CloseConnectionRequest) (*CloseConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseConnection not implemented")
}
func (UnimplementedAdminControlServiceServer) KickUser(context.Context, *KickUserRequest) (*KickUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KickUser not implemented")
}
func (UnimplementedAdminControlServiceServer) DisbandRoom(context.Context, *DisbandRoomRequest) (*DisbandRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisbandRoom not implemented")
}
func (UnimplementedAdminControlServiceServer) RemoveRoomMember(context.Context, *RemoveRoomMemberRequest) (*RemoveRoomMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRoomMember not implemented")
}
func (UnimplementedAdminControlServiceServer) HubStats(context.Context, *emptypb.Empty) (*HubStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HubStats not implemented")
}
func (UnimplementedAdminControlServiceServer) RuntimeSnapshots(context.Context, *emptypb.Empty) (*RuntimeSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RuntimeSnapshots not implemented")
}
func (UnimplementedAdminControlServiceServer) AddAgent(context.Context, *AddAgentRequest) (*AddAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAgent not implemented")
}
func (UnimplementedAdminControlServiceServer) PauseAgent(context.Context, *PauseAgentRequest) (*PauseAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseAgent not implemented")
}
func (UnimplementedAdminControlServiceServer) mustEmbedUnimplementedAdminControlServiceServer() {}
func (UnimplementedAdminControlServiceServer) testEmbeddedByValue()                             {}

// UnsafeAdminControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminControlServiceServer will
// result in compilation errors.
type UnsafeAdminControlServiceServer interface {
	mustEmbedUnimplementedAdminControlServiceServer()
}

func RegisterAdminControlServiceServer(s grpc.ServiceRegistrar, srv AdminControlServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminControlService_ServiceDesc, srv)
}

func _AdminControlService_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).ListConnections(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_CloseConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).CloseConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_CloseConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).CloseConnection(ctx, req.(*CloseConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_KickUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).KickUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_KickUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).KickUser(ctx, req.(*KickUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_DisbandRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisbandRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).DisbandRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_DisbandRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).DisbandRoom(ctx, req.(*DisbandRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_RemoveRoomMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoomMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).RemoveRoomMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_RemoveRoomMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).RemoveRoomMember(ctx, req.(*RemoveRoomMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_HubStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).HubStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_HubStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).HubStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_RuntimeSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).RuntimeSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_RuntimeSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).RuntimeSnapshots(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_AddAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).AddAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_AddAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).AddAgent(ctx, req.(*AddAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminControlService_PauseAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminControlServiceServer).PauseAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminControlService_PauseAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminControlServiceServer).PauseAgent(ctx, req.(*PauseAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminControlService_ServiceDesc is the grpc.ServiceDesc for AdminControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lan_im.admincontrol.v1.AdminControlService",
	HandlerType: (*AdminControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConnections",
			Handler:    _AdminControlService_ListConnections_Handler,
		},
		{
			MethodName: "CloseConnection",
			Handler:    _AdminControlService_CloseConnection_Handler,
		},
		{
			MethodName: "KickUser",
			Handler:    _AdminControlService_KickUser_Handler,
		},
		{
			MethodName: "DisbandRoom",
			Handler:    _AdminControlService_DisbandRoom_Handler,
		},
		{
			MethodName: "RemoveRoomMember",
			Handler:    _AdminControlService_RemoveRoomMember_Handler,
		},
		{
			MethodName: "HubStats",
			Handler:    _AdminControlService_HubStats_Handler,
		},
		{
			MethodName: "RuntimeSnapshots",
			Handler:    _AdminControlService_RuntimeSnapshots_Handler,
		},
		{
			MethodName: "AddAgent",
			Handler:    _AdminControlService_AddAgent_Handler,
		},
		{
			MethodName: "PauseAgent",
			Handler:    _AdminControlService_PauseAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_control.proto",
}
