// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: admin_control.proto

package admincontrolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ConnectionId      string                 `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	RemoteIp          string                 `protobuf:"bytes,4,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	UserAgent         string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ClientVersion     string                 `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ConnectedAtUnixMs int64                  `protobuf:"varint,7,opt,name=connected_at_unix_ms,json=connectedAtUnixMs,proto3" json:"connected_at_unix_ms,omitempty"`
	LastReadAtUnixMs  int64                  `protobuf:"varint,8,opt,name=last_read_at_unix_ms,json=lastReadAtUnixMs,proto3" json:"last_read_at_unix_ms,omitempty"`
	LastWriteAtUnixMs int64                  `protobuf:"varint,9,opt,name=last_write_at_unix_ms,json=lastWriteAtUnixMs,proto3" json:"last_write_at_unix_ms,omitempty"`
	SendQueueLen      int32                  `protobuf:"varint,10,opt,name=send_queue_len,json=sendQueueLen,proto3" json:"send_queue_len,omitempty"`
	RoomIds           []int64                `protobuf:"varint,11,rep,packed,name=room_ids,json=roomIds,proto3" json:"room_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectionSnapshot) Reset() {
	*x = ConnectionSnapshot{}
	mi := &file_admin_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSnapshot) ProtoMessage() {}

func (x *ConnectionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionSnapshot.ProtoReflect.Descriptor instead.
func (*ConnectionSnapshot) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionSnapshot) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConnectionSnapshot) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConnectionSnapshot) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionSnapshot) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *ConnectionSnapshot) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ConnectionSnapshot) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ConnectionSnapshot) GetConnectedAtUnixMs() int64 {
	if x != nil {
		return x.ConnectedAtUnixMs
	}
	return 0
}

func (x *ConnectionSnapshot) GetLastReadAtUnixMs() int64 {
	if x != nil {
		return x.LastReadAtUnixMs
	}
	return 0
}

func (x *ConnectionSnapshot) GetLastWriteAtUnixMs() int64 {
	if x != nil {
		return x.LastWriteAtUnixMs
	}
	return 0
}

func (x *ConnectionSnapshot) GetSendQueueLen() int32 {
	if x != nil {
		return x.SendQueueLen
	}
	return 0
}

func (x *ConnectionSnapshot) GetRoomIds() []int64 {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

type ListConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConnectionSnapshot  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionsResponse) Reset() {
	*x = ListConnectionsResponse{}
	mi := &file_admin_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsResponse) ProtoMessage() {}

func (x *ListConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{1}
}

func (x *ListConnectionsResponse) GetItems() []*ConnectionSnapshot {
	if x != nil {
		return x.Items
	}
	return nil
}

type CloseConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnectionRequest) Reset() {
	*x = CloseConnectionRequest{}
	mi := &file_admin_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnectionRequest) ProtoMessage() {}

func (x *CloseConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnectionRequest.ProtoReflect.Descriptor instead.
func (*CloseConnectionRequest) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{2}
}

func (x *CloseConnectionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type CloseConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnectionResponse) Reset() {
	*x = CloseConnectionResponse{}
	mi := &file_admin_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnectionResponse) ProtoMessage() {}

func (x *CloseConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnectionResponse.ProtoReflect.Descriptor instead.
func (*CloseConnectionResponse) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{3}
}

type KickUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserRequest) Reset() {
	*x = KickUserRequest{}
	mi := &file_admin_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserRequest) ProtoMessage() {}

func (x *KickUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserRequest.ProtoReflect.Descriptor instead.
func (*KickUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{4}
}

func (x *KickUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type KickUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserResponse) Reset() {
	*x = KickUserResponse{}
	mi := &file_admin_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserResponse) ProtoMessage() {}

func (x *KickUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserResponse.ProtoReflect.Descriptor instead.
func (*KickUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{5}
}

type DisbandRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisbandRoomRequest) Reset() {
	*x = DisbandRoomRequest{}
	mi := &file_admin_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisbandRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisbandRoomRequest) ProtoMessage() {}

func (x *DisbandRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisbandRoomRequest.ProtoReflect.Descriptor instead.
func (*DisbandRoomRequest) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{6}
}

func (x *DisbandRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type DisbandRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisbandRoomResponse) Reset() {
	*x = DisbandRoomResponse{}
	mi := &file_admin_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisbandRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisbandRoomResponse) ProtoMessage() {}

func (x *DisbandRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisbandRoomResponse.ProtoReflect.Descriptor instead.
func (*DisbandRoomResponse) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{7}
}

type RemoveRoomMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoomMemberRequest) Reset() {
	*x = RemoveRoomMemberRequest{}
	mi := &file_admin_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomMemberRequest) ProtoMessage() {}

func (x *RemoveRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveRoomMemberRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RemoveRoomMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveRoomMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoomMemberResponse) Reset() {
	*x = RemoveRoomMemberResponse{}
	mi := &file_admin_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoomMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomMemberResponse) ProtoMessage() {}

func (x *RemoveRoomMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveRoomMemberResponse) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{9}
}

type HubStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCount   int64                  `protobuf:"varint,1,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	RoomCount     int64                  `protobuf:"varint,2,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubStatsResponse) Reset() {
	*x = HubStatsResponse{}
	mi := &file_admin_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubStatsResponse) ProtoMessage() {}

func (x *HubStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubStatsResponse.ProtoReflect.Descriptor instead.
func (*HubStatsResponse) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{10}
}

func (x *HubStatsResponse) GetClientCount() int64 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

func (x *HubStatsResponse) GetRoomCount() int64 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

type WebSocketRuntime struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	CurrentConnections          int64                  `protobuf:"varint,1,opt,name=current_connections,json=currentConnections,proto3" json:"current_connections,omitempty"`
	EstablishedTotal            int64                  `protobuf:"varint,2,opt,name=established_total,json=establishedTotal,proto3" json:"established_total,omitempty"`
	ClosedTotal                 int64                  `protobuf:"varint,3,opt,name=closed_total,json=closedTotal,proto3" json:"closed_total,omitempty"`
	AbnormalClosedTotal         int64                  `protobuf:"varint,4,opt,name=abnormal_closed_total,json=abnormalClosedTotal,proto3" json:"abnormal_closed_total,omitempty"`
	AverageConnectionDurationMs float64                `protobuf:"fixed64,5,opt,name=average_connection_duration_ms,json=averageConnectionDurationMs,proto3" json:"average_connection_duration_ms,omitempty"`
	ReadMessagesPerMinute       int64                  `protobuf:"varint,6,opt,name=read_messages_per_minute,json=readMessagesPerMinute,proto3" json:"read_messages_per_minute,omitempty"`
	WriteMessagesPerMinute      int64                  `protobuf:"varint,7,opt,name=write_messages_per_minute,json=writeMessagesPerMinute,proto3" json:"write_messages_per_minute,omitempty"`
	SendQueueBacklog            int64                  `protobuf:"varint,8,opt,name=send_queue_backlog,json=sendQueueBacklog,proto3" json:"send_queue_backlog,omitempty"`
	SlowClients                 int64                  `protobuf:"varint,9,opt,name=slow_clients,json=slowClients,proto3" json:"slow_clients,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *WebSocketRuntime) Reset() {
	*x = WebSocketRuntime{}
	mi := &file_admin_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketRuntime) ProtoMessage() {}

func (x *WebSocketRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketRuntime.ProtoReflect.Descriptor instead.
func (*WebSocketRuntime) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{11}
}

func (x *WebSocketRuntime) GetCurrentConnections() int64 {
	if x != nil {
		return x.CurrentConnections
	}
	return 0
}

func (x *WebSocketRuntime) GetEstablishedTotal() int64 {
	if x != nil {
		return x.EstablishedTotal
	}
	return 0
}

func (x *WebSocketRuntime) GetClosedTotal() int64 {
	if x != nil {
		return x.ClosedTotal
	}
	return 0
}

func (x *WebSocketRuntime) GetAbnormalClosedTotal() int64 {
	if x != nil {
		return x.AbnormalClosedTotal
	}
	return 0
}

func (x *WebSocketRuntime) GetAverageConnectionDurationMs() float64 {
	if x != nil {
		return x.AverageConnectionDurationMs
	}
	return 0
}

func (x *WebSocketRuntime) GetReadMessagesPerMinute() int64 {
	if x != nil {
		return x.ReadMessagesPerMinute
	}
	return 0
}

func (x *WebSocketRuntime) GetWriteMessagesPerMinute() int64 {
	if x != nil {
		return x.WriteMessagesPerMinute
	}
	return 0
}

func (x *WebSocketRuntime) GetSendQueueBacklog() int64 {
	if x != nil {
		return x.SendQueueBacklog
	}
	return 0
}

func (x *WebSocketRuntime) GetSlowClients() int64 {
	if x != nil {
		return x.SlowClients
	}
	return 0
}

type GoRuntime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goroutines    int64                  `protobuf:"varint,1,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	Gomaxprocs    int64                  `protobuf:"varint,2,opt,name=gomaxprocs,proto3" json:"gomaxprocs,omitempty"`
	HeapAlloc     uint64                 `protobuf:"varint,3,opt,name=heap_alloc,json=heapAlloc,proto3" json:"heap_alloc,omitempty"`
	HeapSys       uint64                 `protobuf:"varint,4,opt,name=heap_sys,json=heapSys,proto3" json:"heap_sys,omitempty"`
	GcCount       uint32                 `protobuf:"varint,5,opt,name=gc_count,json=gcCount,proto3" json:"gc_count,omitempty"`
	LastGcUnix    int64                  `protobuf:"varint,6,opt,name=last_gc_unix,json=lastGcUnix,proto3" json:"last_gc_unix,omitempty"`
	GcPauseNs     uint64                 `protobuf:"varint,7,opt,name=gc_pause_ns,json=gcPauseNs,proto3" json:"gc_pause_ns,omitempty"`
	UptimeSeconds float64                `protobuf:"fixed64,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoRuntime) Reset() {
	*x = GoRuntime{}
	mi := &file_admin_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoRuntime) ProtoMessage() {}

func (x *GoRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoRuntime.ProtoReflect.Descriptor instead.
func (*GoRuntime) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{12}
}

func (x *GoRuntime) GetGoroutines() int64 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *GoRuntime) GetGomaxprocs() int64 {
	if x != nil {
		return x.Gomaxprocs
	}
	return 0
}

func (x *GoRuntime) GetHeapAlloc() uint64 {
	if x != nil {
		return x.HeapAlloc
	}
	return 0
}

func (x *GoRuntime) GetHeapSys() uint64 {
	if x != nil {
		return x.HeapSys
	}
	return 0
}

func (x *GoRuntime) GetGcCount() uint32 {
	if x != nil {
		return x.GcCount
	}
	return 0
}

func (x *GoRuntime) GetLastGcUnix() int64 {
	if x != nil {
		return x.LastGcUnix
	}
	return 0
}

func (x *GoRuntime) GetGcPauseNs() uint64 {
	if x != nil {
		return x.GcPauseNs
	}
	return 0
}

func (x *GoRuntime) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type APIRuntime struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Qps_1M           float64                `protobuf:"fixed64,1,opt,name=qps_1m,json=qps1m,proto3" json:"qps_1m,omitempty"`
	Qps_5M           float64                `protobuf:"fixed64,2,opt,name=qps_5m,json=qps5m,proto3" json:"qps_5m,omitempty"`
	AverageLatencyMs float64                `protobuf:"fixed64,3,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`
	P50LatencyMs     float64                `protobuf:"fixed64,4,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs     float64                `protobuf:"fixed64,5,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs     float64                `protobuf:"fixed64,6,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	Status_4Xx       int64                  `protobuf:"varint,7,opt,name=status_4xx,json=status4xx,proto3" json:"status_4xx,omitempty"`
	Status_5Xx       int64                  `protobuf:"varint,8,opt,name=status_5xx,json=status5xx,proto3" json:"status_5xx,omitempty"`
	ErrorRate        float64                `protobuf:"fixed64,9,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *APIRuntime) Reset() {
	*x = APIRuntime{}
	mi := &file_admin_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRuntime) ProtoMessage() {}

func (x *APIRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRuntime.ProtoReflect.Descriptor instead.
func (*APIRuntime) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{13}
}

func (x *APIRuntime) GetQps_1M() float64 {
	if x != nil {
		return x.Qps_1M
	}
	return 0
}

func (x *APIRuntime) GetQps_5M() float64 {
	if x != nil {
		return x.Qps_5M
	}
	return 0
}

func (x *APIRuntime) GetAverageLatencyMs() float64 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

func (x *APIRuntime) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *APIRuntime) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *APIRuntime) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *APIRuntime) GetStatus_4Xx() int64 {
	if x != nil {
		return x.Status_4Xx
	}
	return 0
}

func (x *APIRuntime) GetStatus_5Xx() int64 {
	if x != nil {
		return x.Status_5Xx
	}
	return 0
}

func (x *APIRuntime) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

type RuntimeSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Websocket     *WebSocketRuntime      `protobuf:"bytes,1,opt,name=websocket,proto3" json:"websocket,omitempty"`
	Golang        *GoRuntime             `protobuf:"bytes,2,opt,name=golang,proto3" json:"golang,omitempty"`
	Api           *APIRuntime            `protobuf:"bytes,3,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeSnapshot) Reset() {
	*x = RuntimeSnapshot{}
	mi := &file_admin_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSnapshot) ProtoMessage() {}

func (x *RuntimeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSnapshot.ProtoReflect.Descriptor instead.
func (*RuntimeSnapshot) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{14}
}

func (x *RuntimeSnapshot) GetWebsocket() *WebSocketRuntime {
	if x != nil {
		return x.Websocket
	}
	return nil
}

func (x *RuntimeSnapshot) GetGolang() *GoRuntime {
	if x != nil {
		return x.Golang
	}
	return nil
}

func (x *RuntimeSnapshot) GetApi() *APIRuntime {
	if x != nil {
		return x.Api
	}
	return nil
}

type AgentFailureEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixMs    int64                  `protobuf:"varint,1,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"time_unix_ms,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrorType     string                 `protobuf:"bytes,4,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	HttpStatus    int32                  `protobuf:"varint,5,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Retries       int32                  `protobuf:"varint,7,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFailureEvent) Reset() {
	*x = AgentFailureEvent{}
	mi := &file_admin_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFailureEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFailureEvent) ProtoMessage() {}

func (x *AgentFailureEvent) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFailureEvent.ProtoReflect.Descriptor instead.
func (*AgentFailureEvent) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{15}
}

func (x *AgentFailureEvent) GetTimeUnixMs() int64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

func (x *AgentFailureEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentFailureEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentFailureEvent) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *AgentFailureEvent) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *AgentFailureEvent) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AgentFailureEvent) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type AgentRuntimeSnapshot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CallsToday           int64                  `protobuf:"varint,1,opt,name=calls_today,json=callsToday,proto3" json:"calls_today,omitempty"`
	CurrentRequests      int64                  `protobuf:"varint,2,opt,name=current_requests,json=currentRequests,proto3" json:"current_requests,omitempty"`
	SuccessRate          float64                `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	FailureRate          float64                `protobuf:"fixed64,4,opt,name=failure_rate,json=failureRate,proto3" json:"failure_rate,omitempty"`
	AverageResponseMs    float64                `protobuf:"fixed64,5,opt,name=average_response_ms,json=averageResponseMs,proto3" json:"average_response_ms,omitempty"`
	P95ResponseMs        float64                `protobuf:"fixed64,6,opt,name=p95_response_ms,json=p95ResponseMs,proto3" json:"p95_response_ms,omitempty"`
	TotalTokens          int64                  `protobuf:"varint,7,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	InputTokens          int64                  `protobuf:"varint,8,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens         int64                  `protobuf:"varint,9,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	AverageTokensPerCall float64                `protobuf:"fixed64,10,opt,name=average_tokens_per_call,json=averageTokensPerCall,proto3" json:"average_tokens_per_call,omitempty"`
	ToolCalls            int64                  `protobuf:"varint,11,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolSuccessRate      float64                `protobuf:"fixed64,12,opt,name=tool_success_rate,json=toolSuccessRate,proto3" json:"tool_success_rate,omitempty"`
	RagCalls             int64                  `protobuf:"varint,13,opt,name=rag_calls,json=ragCalls,proto3" json:"rag_calls,omitempty"`
	TimeToolCalls        int64                  `protobuf:"varint,14,opt,name=time_tool_calls,json=timeToolCalls,proto3" json:"time_tool_calls,omitempty"`
	ModerationCalls      int64                  `protobuf:"varint,15,opt,name=moderation_calls,json=moderationCalls,proto3" json:"moderation_calls,omitempty"`
	EmbeddingCalls       int64                  `protobuf:"varint,16,opt,name=embedding_calls,json=embeddingCalls,proto3" json:"embedding_calls,omitempty"`
	EmbeddingFailures    int64                  `protobuf:"varint,17,opt,name=embedding_failures,json=embeddingFailures,proto3" json:"embedding_failures,omitempty"`
	RecentFailures       []*AgentFailureEvent   `protobuf:"bytes,18,rep,name=recent_failures,json=recentFailures,proto3" json:"recent_failures,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AgentRuntimeSnapshot) Reset() {
	*x = AgentRuntimeSnapshot{}
	mi := &file_admin_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRuntimeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRuntimeSnapshot) ProtoMessage() {}

func (x *AgentRuntimeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRuntimeSnapshot.ProtoReflect.Descriptor instead.
func (*AgentRuntimeSnapshot) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{16}
}

func (x *AgentRuntimeSnapshot) GetCallsToday() int64 {
	if x != nil {
		return x.CallsToday
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetCurrentRequests() int64 {
	if x != nil {
		return x.CurrentRequests
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetFailureRate() float64 {
	if x != nil {
		return x.FailureRate
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetAverageResponseMs() float64 {
	if x != nil {
		return x.AverageResponseMs
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetP95ResponseMs() float64 {
	if x != nil {
		return x.P95ResponseMs
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetAverageTokensPerCall() float64 {
	if x != nil {
		return x.AverageTokensPerCall
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetToolCalls() int64 {
	if x != nil {
		return x.ToolCalls
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetToolSuccessRate() float64 {
	if x != nil {
		return x.ToolSuccessRate
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetRagCalls() int64 {
	if x != nil {
		return x.RagCalls
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetTimeToolCalls() int64 {
	if x != nil {
		return x.TimeToolCalls
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetModerationCalls() int64 {
	if x != nil {
		return x.ModerationCalls
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetEmbeddingCalls() int64 {
	if x != nil {
		return x.EmbeddingCalls
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetEmbeddingFailures() int64 {
	if x != nil {
		return x.EmbeddingFailures
	}
	return 0
}

func (x *AgentRuntimeSnapshot) GetRecentFailures() []*AgentFailureEvent {
	if x != nil {
		return x.RecentFailures
	}
	return nil
}

type RuntimeSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       *RuntimeSnapshot       `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Agent         *AgentRuntimeSnapshot  `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeSnapshotsResponse) Reset() {
	*x = RuntimeSnapshotsResponse{}
	mi := &file_admin_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSnapshotsResponse) ProtoMessage() {}

func (x *RuntimeSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*RuntimeSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{17}
}

func (x *RuntimeSnapshotsResponse) GetRuntime() *RuntimeSnapshot {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *RuntimeSnapshotsResponse) GetAgent() *AgentRuntimeSnapshot {
	if x != nil {
		return x.Agent
	}
	return nil
}

type AddAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAgentRequest) Reset() {
	*x = AddAgentRequest{}
	mi := &file_admin_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgentRequest) ProtoMessage() {}

func (x *AddAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgentRequest.ProtoReflect.Descriptor instead.
func (*AddAgentRequest) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{18}
}

func (x *AddAgentRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type AddAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAgentResponse) Reset() {
	*x = AddAgentResponse{}
	mi := &file_admin_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgentResponse) ProtoMessage() {}

func (x *AddAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgentResponse.ProtoReflect.Descriptor instead.
func (*AddAgentResponse) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{19}
}

type PauseAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseAgentRequest) Reset() {
	*x = PauseAgentRequest{}
	mi := &file_admin_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseAgentRequest) ProtoMessage() {}

func (x *PauseAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseAgentRequest.ProtoReflect.Descriptor instead.
func (*PauseAgentRequest) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{20}
}

func (x *PauseAgentRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type PauseAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseAgentResponse) Reset() {
	*x = PauseAgentResponse{}
	mi := &file_admin_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseAgentResponse) ProtoMessage() {}

func (x *PauseAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseAgentResponse.ProtoReflect.Descriptor instead.
func (*PauseAgentResponse) Descriptor() ([]byte, []int) {
	return file_admin_control_proto_rawDescGZIP(), []int{21}
}

var File_admin_control_proto protoreflect.FileDescriptor

const file_admin_control_proto_rawDesc = "" +
	"\n" +
	"\x13admin_control.proto\x12\x16lan_im.admincontrol.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xa5\x03\n" +
	"\x12ConnectionSnapshot\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\x12\x1b\n" +
	"\tremote_ip\x18\x04 \x01(\tR\bremoteIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12%\n" +
	"\x0eclient_version\x18\x06 \x01(\tR\rclientVersion\x12/\n" +
	"\x14connected_at_unix_ms\x18\a \x01(\x03R\x11connectedAtUnixMs\x12.\n" +
	"\x14last_read_at_unix_ms\x18\b \x01(\x03R\x10lastReadAtUnixMs\x120\n" +
	"\x15last_write_at_unix_ms\x18\t \x01(\x03R\x11lastWriteAtUnixMs\x12$\n" +
	"\x0esend_queue_len\x18\n" +
	" \x01(\x05R\fsendQueueLen\x12\x19\n" +
	"\broom_ids\x18\v \x03(\x03R\aroomIds\"[\n" +
	"\x17ListConnectionsResponse\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.lan_im.admincontrol.v1.ConnectionSnapshotR\x05items\"=\n" +
	"\x16CloseConnectionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\x19\n" +
	"\x17CloseConnectionResponse\"*\n" +
	"\x0fKickUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x12\n" +
	"\x10KickUserResponse\"-\n" +
	"\x12DisbandRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"\x15\n" +
	"\x13DisbandRoomResponse\"K\n" +
	"\x17RemoveRoomMemberRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x1a\n" +
	"\x18RemoveRoomMemberResponse\"T\n" +
	"\x10HubStatsResponse\x12!\n" +
	"\fclient_count\x18\x01 \x01(\x03R\vclientCount\x12\x1d\n" +
	"\n" +
	"room_count\x18\x02 \x01(\x03R\troomCount\"\xd1\x03\n" +
	"\x10WebSocketRuntime\x12/\n" +
	"\x13current_connections\x18\x01 \x01(\x03R\x12currentConnections\x12+\n" +
	"\x11established_total\x18\x02 \x01(\x03R\x10establishedTotal\x12!\n" +
	"\fclosed_total\x18\x03 \x01(\x03R\vclosedTotal\x122\n" +
	"\x15abnormal_closed_total\x18\x04 \x01(\x03R\x13abnormalClosedTotal\x12C\n" +
	"\x1eaverage_connection_duration_ms\x18\x05 \x01(\x01R\x1baverageConnectionDurationMs\x127\n" +
	"\x18read_messages_per_minute\x18\x06 \x01(\x03R\x15readMessagesPerMinute\x129\n" +
	"\x19write_messages_per_minute\x18\a \x01(\x03R\x16writeMessagesPerMinute\x12,\n" +
	"\x12send_queue_backlog\x18\b \x01(\x03R\x10sendQueueBacklog\x12!\n" +
	"\fslow_clients\x18\t \x01(\x03R\vslowClients\"\x89\x02\n" +
	"\tGoRuntime\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x01 \x01(\x03R\n" +
	"goroutines\x12\x1e\n" +
	"\n" +
	"gomaxprocs\x18\x02 \x01(\x03R\n" +
	"gomaxprocs\x12\x1d\n" +
	"\n" +
	"heap_alloc\x18\x03 \x01(\x04R\theapAlloc\x12\x19\n" +
	"\bheap_sys\x18\x04 \x01(\x04R\aheapSys\x12\x19\n" +
	"\bgc_count\x18\x05 \x01(\rR\agcCount\x12 \n" +
	"\flast_gc_unix\x18\x06 \x01(\x03R\n" +
	"lastGcUnix\x12\x1e\n" +
	"\vgc_pause_ns\x18\a \x01(\x04R\tgcPauseNs\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x01R\ruptimeSeconds\"\xb7\x02\n" +
	"\n" +
	"APIRuntime\x12\x15\n" +
	"\x06qps_1m\x18\x01 \x01(\x01R\x05qps1m\x12\x15\n" +
	"\x06qps_5m\x18\x02 \x01(\x01R\x05qps5m\x12,\n" +
	"\x12average_latency_ms\x18\x03 \x01(\x01R\x10averageLatencyMs\x12$\n" +
	"\x0ep50_latency_ms\x18\x04 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x05 \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x06 \x01(\x01R\fp99LatencyMs\x12\x1d\n" +
	"\n" +
	"status_4xx\x18\a \x01(\x03R\tstatus4xx\x12\x1d\n" +
	"\n" +
	"status_5xx\x18\b \x01(\x03R\tstatus5xx\x12\x1d\n" +
	"\n" +
	"error_rate\x18\t \x01(\x01R\terrorRate\"\xca\x01\n" +
	"\x0fRuntimeSnapshot\x12F\n" +
	"\twebsocket\x18\x01 \x01(\v2(.lan_im.admincontrol.v1.WebSocketRuntimeR\twebsocket\x129\n" +
	"\x06golang\x18\x02 \x01(\v2!.lan_im.admincontrol.v1.GoRuntimeR\x06golang\x124\n" +
	"\x03api\x18\x03 \x01(\v2\".lan_im.admincontrol.v1.APIRuntimeR\x03api\"\xe3\x01\n" +
	"\x11AgentFailureEvent\x12 \n" +
	"\ftime_unix_ms\x18\x01 \x01(\x03R\n" +
	"timeUnixMs\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"error_type\x18\x04 \x01(\tR\terrorType\x12\x1f\n" +
	"\vhttp_status\x18\x05 \x01(\x05R\n" +
	"httpStatus\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x01R\tlatencyMs\x12\x18\n" +
	"\aretries\x18\a \x01(\x05R\aretries\"\x89\x06\n" +
	"\x14AgentRuntimeSnapshot\x12\x1f\n" +
	"\vcalls_today\x18\x01 \x01(\x03R\n" +
	"callsToday\x12)\n" +
	"\x10current_requests\x18\x02 \x01(\x03R\x0fcurrentRequests\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x01R\vsuccessRate\x12!\n" +
	"\ffailure_rate\x18\x04 \x01(\x01R\vfailureRate\x12.\n" +
	"\x13average_response_ms\x18\x05 \x01(\x01R\x11averageResponseMs\x12&\n" +
	"\x0fp95_response_ms\x18\x06 \x01(\x01R\rp95ResponseMs\x12!\n" +
	"\ftotal_tokens\x18\a \x01(\x03R\vtotalTokens\x12!\n" +
	"\finput_tokens\x18\b \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\t \x01(\x03R\foutputTokens\x125\n" +
	"\x17average_tokens_per_call\x18\n" +
	" \x01(\x01R\x14averageTokensPerCall\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\v \x01(\x03R\ttoolCalls\x12*\n" +
	"\x11tool_success_rate\x18\f \x01(\x01R\x0ftoolSuccessRate\x12\x1b\n" +
	"\trag_calls\x18\r \x01(\x03R\bragCalls\x12&\n" +
	"\x0ftime_tool_calls\x18\x0e \x01(\x03R\rtimeToolCalls\x12)\n" +
	"\x10moderation_calls\x18\x0f \x01(\x03R\x0fmoderationCalls\x12'\n" +
	"\x0fembedding_calls\x18\x10 \x01(\x03R\x0eembeddingCalls\x12-\n" +
	"\x12embedding_failures\x18\x11 \x01(\x03R\x11embeddingFailures\x12R\n" +
	"\x0frecent_failures\x18\x12 \x03(\v2).lan_im.admincontrol.v1.AgentFailureEventR\x0erecentFailures\"\xa1\x01\n" +
	"\x18RuntimeSnapshotsResponse\x12A\n" +
	"\aruntime\x18\x01 \x01(\v2'.lan_im.admincontrol.v1.RuntimeSnapshotR\aruntime\x12B\n" +
	"\x05agent\x18\x02 \x01(\v2,.lan_im.admincontrol.v1.AgentRuntimeSnapshotR\x05agent\"*\n" +
	"\x0fAddAgentRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"\x12\n" +
	"\x10AddAgentResponse\",\n" +
	"\x11PauseAgentRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"\x14\n" +
	"\x12PauseAgentResponse2\x93\a\n" +
	"\x13AdminControlService\x12Z\n" +
	"\x0fListConnections\x12\x16.google.protobuf.Empty\x1a/.lan_im.admincontrol.v1.ListConnectionsResponse\x12r\n" +
	"\x0fCloseConnection\x12..lan_im.admincontrol.v1.CloseConnectionRequest\x1a/.lan_im.admincontrol.v1.CloseConnectionResponse\x12]\n" +
	"\bKickUser\x12'.lan_im.admincontrol.v1.KickUserRequest\x1a(.lan_im.admincontrol.v1.KickUserResponse\x12f\n" +
	"\vDisbandRoom\x12*.lan_im.admincontrol.v1.DisbandRoomRequest\x1a+.lan_im.admincontrol.v1.DisbandRoomResponse\x12u\n" +
	"\x10RemoveRoomMember\x12/.lan_im.admincontrol.v1.RemoveRoomMemberRequest\x1a0.lan_im.admincontrol.v1.RemoveRoomMemberResponse\x12L\n" +
	"\bHubStats\x12\x16.google.protobuf.Empty\x1a(.lan_im.admincontrol.v1.HubStatsResponse\x12\\\n" +
	"\x10RuntimeSnapshots\x12\x16.google.protobuf.Empty\x1a0.lan_im.admincontrol.v1.RuntimeSnapshotsResponse\x12]\n" +
	"\bAddAgent\x12'.lan_im.admincontrol.v1.AddAgentRequest\x1a(.lan_im.admincontrol.v1.AddAgentResponse\x12c\n" +
	"\n" +
	"PauseAgent\x12).lan_im.admincontrol.v1.PauseAgentRequest\x1a*.lan_im.admincontrol.v1.PauseAgentResponseB0Z.lan-im-go/proto/admincontrol/v1;admincontrolv1b\x06proto3"

var (
	file_admin_control_proto_rawDescOnce sync.Once
	file_admin_control_proto_rawDescData []byte
)

func file_admin_control_proto_rawDescGZIP() []byte {
	file_admin_control_proto_rawDescOnce.Do(func() {
		file_admin_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_control_proto_rawDesc), len(file_admin_control_proto_rawDesc)))
	})
	return file_admin_control_proto_rawDescData
}

var file_admin_control_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_admin_control_proto_goTypes = []any{
	(*ConnectionSnapshot)(nil),       // 0: lan_im.admincontrol.v1.ConnectionSnapshot
	(*ListConnectionsResponse)(nil),  // 1: lan_im.admincontrol.v1.ListConnectionsResponse
	(*CloseConnectionRequest)(nil),   // 2: lan_im.admincontrol.v1.CloseConnectionRequest
	(*CloseConnectionResponse)(nil),  // 3: lan_im.admincontrol.v1.CloseConnectionResponse
	(*KickUserRequest)(nil),          // 4: lan_im.admincontrol.v1.KickUserRequest
	(*KickUserResponse)(nil),         // 5: lan_im.admincontrol.v1.KickUserResponse
	(*DisbandRoomRequest)(nil),       // 6: lan_im.admincontrol.v1.DisbandRoomRequest
	(*DisbandRoomResponse)(nil),      // 7: lan_im.admincontrol.v1.DisbandRoomResponse
	(*RemoveRoomMemberRequest)(nil),  // 8: lan_im.admincontrol.v1.RemoveRoomMemberRequest
	(*RemoveRoomMemberResponse)(nil), // 9: lan_im.admincontrol.v1.RemoveRoomMemberResponse
	(*HubStatsResponse)(nil),         // 10: lan_im.admincontrol.v1.HubStatsResponse
	(*WebSocketRuntime)(nil),         // 11: lan_im.admincontrol.v1.WebSocketRuntime
	(*GoRuntime)(nil),                // 12: lan_im.admincontrol.v1.GoRuntime
	(*APIRuntime)(nil),               // 13: lan_im.admincontrol.v1.APIRuntime
	(*RuntimeSnapshot)(nil),          // 14: lan_im.admincontrol.v1.RuntimeSnapshot
	(*AgentFailureEvent)(nil),        // 15: lan_im.admincontrol.v1.AgentFailureEvent
	(*AgentRuntimeSnapshot)(nil),     // 16: lan_im.admincontrol.v1.AgentRuntimeSnapshot
	(*RuntimeSnapshotsResponse)(nil), // 17: lan_im.admincontrol.v1.RuntimeSnapshotsResponse
	(*AddAgentRequest)(nil),          // 18: lan_im.admincontrol.v1.AddAgentRequest
	(*AddAgentResponse)(nil),         // 19: lan_im.admincontrol.v1.AddAgentResponse
	(*PauseAgentRequest)(nil),        // 20: lan_im.admincontrol.v1.PauseAgentRequest
	(*PauseAgentResponse)(nil),       // 21: lan_im.admincontrol.v1.PauseAgentResponse
	(*emptypb.Empty)(nil),            // 22: google.protobuf.Empty
}
var file_admin_control_proto_depIdxs = []int32{
	0,  // 0: lan_im.admincontrol.v1.ListConnectionsResponse.items:type_name -> lan_im.admincontrol.v1.ConnectionSnapshot
	11, // 1: lan_im.admincontrol.v1.RuntimeSnapshot.websocket:type_name -> lan_im.admincontrol.v1.WebSocketRuntime
	12, // 2: lan_im.admincontrol.v1.RuntimeSnapshot.golang:type_name -> lan_im.admincontrol.v1.GoRuntime
	13, // 3: lan_im.admincontrol.v1.RuntimeSnapshot.api:type_name -> lan_im.admincontrol.v1.APIRuntime
	15, // 4: lan_im.admincontrol.v1.AgentRuntimeSnapshot.recent_failures:type_name -> lan_im.admincontrol.v1.AgentFailureEvent
	14, // 5: lan_im.admincontrol.v1.RuntimeSnapshotsResponse.runtime:type_name -> lan_im.admincontrol.v1.RuntimeSnapshot
	16, // 6: lan_im.admincontrol.v1.RuntimeSnapshotsResponse.agent:type_name -> lan_im.admincontrol.v1.AgentRuntimeSnapshot
	22, // 7: lan_im.admincontrol.v1.AdminControlService.ListConnections:input_type -> google.protobuf.Empty
	2,  // 8: lan_im.admincontrol.v1.AdminControlService.CloseConnection:input_type -> lan_im.admincontrol.v1.CloseConnectionRequest
	4,  // 9: lan_im.admincontrol.v1.AdminControlService.KickUser:input_type -> lan_im.admincontrol.v1.KickUserRequest
	6,  // 10: lan_im.admincontrol.v1.AdminControlService.DisbandRoom:input_type -> lan_im.admincontrol.v1.DisbandRoomRequest
	8,  // 11: lan_im.admincontrol.v1.AdminControlService.RemoveRoomMember:input_type -> lan_im.admincontrol.v1.RemoveRoomMemberRequest
	22, // 12: lan_im.admincontrol.v1.AdminControlService.HubStats:input_type -> google.protobuf.Empty
	22, // 13: lan_im.admincontrol.v1.AdminControlService.RuntimeSnapshots:input_type -> google.protobuf.Empty
	18, // 14: lan_im.admincontrol.v1.AdminControlService.AddAgent:input_type -> lan_im.admincontrol.v1.AddAgentRequest
	20, // 15: lan_im.admincontrol.v1.AdminControlService.PauseAgent:input_type -> lan_im.admincontrol.v1.PauseAgentRequest
	1,  // 16: lan_im.admincontrol.v1.AdminControlService.ListConnections:output_type -> lan_im.admincontrol.v1.ListConnectionsResponse
	3,  // 17: lan_im.admincontrol.v1.AdminControlService.CloseConnection:output_type -> lan_im.admincontrol.v1.CloseConnectionResponse
	5,  // 18: lan_im.admincontrol.v1.AdminControlService.KickUser:output_type -> lan_im.admincontrol.v1.KickUserResponse
	7,  // 19: lan_im.admincontrol.v1.AdminControlService.DisbandRoom:output_type -> lan_im.admincontrol.v1.DisbandRoomResponse
	9,  // 20: lan_im.admincontrol.v1.AdminControlService.RemoveRoomMember:output_type -> lan_im.admincontrol.v1.RemoveRoomMemberResponse
	10, // 21: lan_im.admincontrol.v1.AdminControlService.HubStats:output_type -> lan_im.admincontrol.v1.HubStatsResponse
	17, // 22: lan_im.admincontrol.v1.AdminControlService.RuntimeSnapshots:output_type -> lan_im.admincontrol.v1.RuntimeSnapshotsResponse
	19, // 23: lan_im.admincontrol.v1.AdminControlService.AddAgent:output_type -> lan_im.admincontrol.v1.AddAgentResponse
	21, // 24: lan_im.admincontrol.v1.AdminControlService.PauseAgent:output_type -> lan_im.admincontrol.v1.PauseAgentResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_admin_control_proto_init() }
func file_admin_control_proto_init() {
	if File_admin_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_control_proto_rawDesc), len(file_admin_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_control_proto_goTypes,
		DependencyIndexes: file_admin_control_proto_depIdxs,
		MessageInfos:      file_admin_control_proto_msgTypes,
	}.Build()
	File_admin_control_proto = out.File
	file_admin_control_proto_goTypes = nil
	file_admin_control_proto_depIdxs = nil
}
