// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/im/v1/message.proto

package imv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,3,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAtNs   int64                  `protobuf:"varint,6,opt,name=created_at_ns,json=createdAtNs,proto3" json:"created_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_im_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_im_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_im_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *ChatMessage) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAtNs() int64 {
	if x != nil {
		return x.CreatedAtNs
	}
	return 0
}

var File_proto_im_v1_message_proto protoreflect.FileDescriptor

const file_proto_im_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x19proto/im/v1/message.proto\x12\flan_im.im.v1\"\xb9\x01\n" +
	"\vChatMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12\"\n" +
	"\rclient_msg_id\x18\x03 \x01(\tR\vclientMsgId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\"\n" +
	"\rcreated_at_ns\x18\x06 \x01(\x03R\vcreatedAtNsB\x1cZ\x1alan-im-go/proto/im/v1;imv1b\x06proto3"

var (
	file_proto_im_v1_message_proto_rawDescOnce sync.Once
	file_proto_im_v1_message_proto_rawDescData []byte
)

func file_proto_im_v1_message_proto_rawDescGZIP() []byte {
	file_proto_im_v1_message_proto_rawDescOnce.Do(func() {
		file_proto_im_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_im_v1_message_proto_rawDesc), len(file_proto_im_v1_message_proto_rawDesc)))
	})
	return file_proto_im_v1_message_proto_rawDescData
}

var file_proto_im_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_im_v1_message_proto_goTypes = []any{
	(*ChatMessage)(nil), // 0: lan_im.im.v1.ChatMessage
}
var file_proto_im_v1_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_im_v1_message_proto_init() }
func file_proto_im_v1_message_proto_init() {
	if File_proto_im_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_im_v1_message_proto_rawDesc), len(file_proto_im_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_im_v1_message_proto_goTypes,
		DependencyIndexes: file_proto_im_v1_message_proto_depIdxs,
		MessageInfos:      file_proto_im_v1_message_proto_msgTypes,
	}.Build()
	File_proto_im_v1_message_proto = out.File
	file_proto_im_v1_message_proto_goTypes = nil
	file_proto_im_v1_message_proto_depIdxs = nil
}
