# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent.v1 import agent_pb2 as agent_dot_v1_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMessage = channel.unary_unary(
                '/lan_im.agent.v1.AgentService/ProcessMessage',
                request_serializer=agent_dot_v1_dot_agent__pb2.ProcessMessageRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.ProcessMessageResponse.FromString,
                _registered_method=True)
        self.EnableAgent = channel.unary_unary(
                '/lan_im.agent.v1.AgentService/EnableAgent',
                request_serializer=agent_dot_v1_dot_agent__pb2.EnableAgentRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.EnableAgentResponse.FromString,
                _registered_method=True)
        self.PauseAgent = channel.unary_unary(
                '/lan_im.agent.v1.AgentService/PauseAgent',
                request_serializer=agent_dot_v1_dot_agent__pb2.PauseAgentRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.PauseAgentResponse.FromString,
                _registered_method=True)
        self.RemoveAgent = channel.unary_unary(
                '/lan_im.agent.v1.AgentService/RemoveAgent',
                request_serializer=agent_dot_v1_dot_agent__pb2.RemoveAgentRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.RemoveAgentResponse.FromString,
                _registered_method=True)
        self.TriggerChunking = channel.unary_unary(
                '/lan_im.agent.v1.AgentService/TriggerChunking',
                request_serializer=agent_dot_v1_dot_agent__pb2.TriggerChunkingRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.TriggerChunkingResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/lan_im.agent.v1.AgentService/Health',
                request_serializer=agent_dot_v1_dot_agent__pb2.HealthRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.HealthResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerChunking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMessage,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.ProcessMessageRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.ProcessMessageResponse.SerializeToString,
            ),
            'EnableAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableAgent,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.EnableAgentRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.EnableAgentResponse.SerializeToString,
            ),
            'PauseAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseAgent,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.PauseAgentRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.PauseAgentResponse.SerializeToString,
            ),
            'RemoveAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAgent,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.RemoveAgentRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.RemoveAgentResponse.SerializeToString,
            ),
            'TriggerChunking': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerChunking,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.TriggerChunkingRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.TriggerChunkingResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.HealthRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lan_im.agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lan_im.agent.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lan_im.agent.v1.AgentService/ProcessMessage',
            agent_dot_v1_dot_agent__pb2.ProcessMessageRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.ProcessMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lan_im.agent.v1.AgentService/EnableAgent',
            agent_dot_v1_dot_agent__pb2.EnableAgentRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.EnableAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lan_im.agent.v1.AgentService/PauseAgent',
            agent_dot_v1_dot_agent__pb2.PauseAgentRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.PauseAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lan_im.agent.v1.AgentService/RemoveAgent',
            agent_dot_v1_dot_agent__pb2.RemoveAgentRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.RemoveAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerChunking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lan_im.agent.v1.AgentService/TriggerChunking',
            agent_dot_v1_dot_agent__pb2.TriggerChunkingRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.TriggerChunkingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lan_im.agent.v1.AgentService/Health',
            agent_dot_v1_dot_agent__pb2.HealthRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IMServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchMessages = channel.unary_unary(
                '/lan_im.agent.v1.IMService/FetchMessages',
                request_serializer=agent_dot_v1_dot_agent__pb2.FetchMessagesRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.FetchMessagesResponse.FromString,
                _registered_method=True)
        self.KickUser = channel.unary_unary(
                '/lan_im.agent.v1.IMService/KickUser',
                request_serializer=agent_dot_v1_dot_agent__pb2.KickUserRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.KickUserResponse.FromString,
                _registered_method=True)
        self.SendReply = channel.unary_unary(
                '/lan_im.agent.v1.IMService/SendReply',
                request_serializer=agent_dot_v1_dot_agent__pb2.SendReplyRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.SendReplyResponse.FromString,
                _registered_method=True)


class IMServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def FetchMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KickUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchMessages,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.FetchMessagesRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.FetchMessagesResponse.SerializeToString,
            ),
            'KickUser': grpc.unary_unary_rpc_method_handler(
                    servicer.KickUser,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.KickUserRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.KickUserResponse.SerializeToString,
            ),
            'SendReply': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReply,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.SendReplyRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.SendReplyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lan_im.agent.v1.IMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lan_im.agent.v1.IMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IMService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lan_im.agent.v1.IMService/FetchMessages',
            agent_dot_v1_dot_agent__pb2.FetchMessagesRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.FetchMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KickUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lan_im.agent.v1.IMService/KickUser',
            agent_dot_v1_dot_agent__pb2.KickUserRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.KickUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lan_im.agent.v1.IMService/SendReply',
            agent_dot_v1_dot_agent__pb2.SendReplyRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.SendReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
