<template>
  <div class="auth-page"><div class="auth-wrap"><section class="brand-panel"><AppLogo/><div class="hero"><span class="eyebrow">Golang · WebSocket · Agent</span><h1>实时通信与<br/>智能内容治理</h1><p>轻量、高并发的 LAN IM。运营、审核员与管理员在独立后台处理用户、群聊、文件和内容治理。</p></div><div class="mini"><span>WebSocket</span><span>RAG / Qdrant</span><span>Tool Calling</span></div></section><section class="form-card app-card"><h2>欢迎回来</h2><p>登录 LAN IM 工作区</p><form @submit.prevent="submit"><label>用户名</label><input v-model="form.username" class="input" autocomplete="username" placeholder="请输入用户名"/><label>密码</label><input v-model="form.password" class="input" type="password" autocomplete="current-password" placeholder="请输入密码"/><div v-if="error" class="error">{{error}}</div><button class="btn btn-primary submit" :disabled="loading">{{loading?'登录中…':'登录'}}</button></form><div class="footer">还没有账号？<RouterLink to="/register">创建账号</RouterLink></div></section></div></div>
</template>
<script setup>
import { reactive, ref } from 'vue'; import { useRouter,useRoute } from 'vue-router'; import AppLogo from '../components/common/AppLogo.vue'; import { useAuthStore } from '../stores/auth.js'
const form=reactive({username:'',password:''}),error=ref(''),loading=ref(false),auth=useAuthStore(),router=useRouter(),route=useRoute()
async function submit(){error.value='';loading.value=true;try{await auth.login(form);router.replace(route.query.redirect|| (auth.isAdmin?'/admin/users':'/chat'))}catch(e){error.value=e.message}finally{loading.value=false}}
</script>
<style scoped>
.auth-page{min-height:100vh;display:grid;place-items:center;padding:28px;background:radial-gradient(circle at 20% 0%,rgba(49,89,232,.10),transparent 30%),var(--bg)}.auth-wrap{width:min(980px,100%);display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.brand-panel{min-height:520px;border-radius:18px;padding:30px;background:linear-gradient(145deg,#111a31,#1f2f59);color:#fff;display:flex;flex-direction:column;justify-content:space-between;box-shadow:var(--shadow-md)}.hero{max-width:560px}.eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#91a9ff}.hero h1{font-size:38px;line-height:1.2;letter-spacing:-.035em;margin:16px 0}.hero p{color:#bec9dd;line-height:1.8}.mini{display:flex;gap:8px;flex-wrap:wrap}.mini span{padding:6px 9px;border:1px solid rgba(255,255,255,.14);border-radius:999px;color:#c9d3e7;font-size:11px}.form-card{padding:34px;align-self:center}.form-card h2{font-size:24px;margin:0}.form-card>p{color:var(--text-2);margin:7px 0 26px}form{display:grid;gap:10px}label{font-size:12px;font-weight:650;margin-top:4px}.submit{margin-top:10px;height:42px}.error{padding:9px 10px;border-radius:8px;background:var(--danger-soft);color:var(--danger);font-size:12px}.footer{text-align:center;margin-top:20px;color:var(--text-3);font-size:12px}.footer a{color:var(--primary);font-weight:650}@media(max-width:760px){.auth-wrap{grid-template-columns:1fr}.brand-panel{display:none}}
</style>
